version: '3'

services:
  backend:
    command: bash -c "npm install && node ."
    env_file: .env
    image: node:carbon
    ports:
      - 80:80
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app